### ISSUE TITLE
Panorama View: Hostgroup status not fully loaded - JS Error

### ISSUE THREAD

**Issue by kafos** [sni/Thruk#1281]
**Describe the bug**
Opening a map with the hostgroup status on it, panorama view often fails to fully load the status.

in the thruk.log the following error comes up:

[2023/06/04 22:59:16][NagiosNode2][ERROR] JS-Error:
[2023/06/04 22:59:16][NagiosNode2][ERROR] Version:    3.05.20230520/ OMD 5.11~2023-05-20-labs-edition
[2023/06/04 22:59:16][NagiosNode2][ERROR] Release:    May 20, 2023
[2023/06/04 22:59:16][NagiosNode2][ERROR] Url:        /XX/thruk/cgi-bin/panorama.cgi?
[2023/06/04 22:59:16][NagiosNode2][ERROR] Browser:    Chrome 113.0.0.0 on Windows 10 64-bit
[2023/06/04 22:59:16][NagiosNode2][ERROR] UserAgent:  Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/113.0.0.0 Saf                                 ari/537.36
[2023/06/04 22:59:16][NagiosNode2][ERROR] User:       omiller
[2023/06/04 22:59:16][NagiosNode2][ERROR] Backends:   2 / null / null
[2023/06/04 22:59:16][NagiosNode2][ERROR]             2 / null / null
[2023/06/04 22:59:16][NagiosNode2][ERROR]             2 / null / null
[2023/06/04 22:59:16][NagiosNode2][ERROR]             2 / null / null
[2023/06/04 22:59:16][NagiosNode2][ERROR]             2 / null / null
[2023/06/04 22:59:16][NagiosNode2][ERROR]             2 / null / null
[2023/06/04 22:59:16][NagiosNode2][ERROR]             2 / null / null
[2023/06/04 22:59:16][NagiosNode2][ERROR]             2 / null / null
[2023/06/04 22:59:16][NagiosNode2][ERROR]             0 / 1.4.1 / Livestatus 1.4.1-naemon
[2023/06/04 22:59:16][NagiosNode2][ERROR]             2 / null / null
[2023/06/04 22:59:16][NagiosNode2][ERROR]             0 / 1.4.1 / Livestatus 1.4.1-naemon (via Thruk 3.05.20230520)
[2023/06/04 22:59:16][NagiosNode2][ERROR] Error List:
[2023/06/04 22:59:16][NagiosNode2][ERROR] Url: https://ZZZZZ/XXthruk/cache/thruk-panorama-3.05.20230520.js Line 16642
[2023/06/04 22:59:16][NagiosNode2][ERROR] Error: Uncaught TypeError: Cannot read properties of undefined (reading 'id')
[2023/06/04 22:59:16][NagiosNode2][ERROR] Full Stacktrace:
[2023/06/04 22:59:16][NagiosNode2][ERROR] TypeError: Cannot read properties of undefined (reading 'id')
[2023/06/04 22:59:16][NagiosNode2][ERROR]     at callback (https://ZZZZZ/XX/pv/thruk/cache/thruk-panorama-3.05.20230520.js:16642:42)
[2023/06/04 22:59:16][NagiosNode2][ERROR]     at Object.callback (https://ZZZZZ/XX/thruk/vendor/extjs-4.2.2/ext-all.js:21:81113)
[2023/06/04 22:59:16][NagiosNode2][ERROR]     at A.onComplete (https://ZZZZZ/XXthruk/vendor/extjs-4.2.2/ext-all.js:21:368138)
[2023/06/04 22:59:16][NagiosNode2][ERROR]     at A.onStateChange (https://ZZZZZ/XX/thruk/vendor/extjs-4.2.2/ext-all.js:21:367479)
[2023/06/04 22:59:16][NagiosNode2][ERROR]     at XMLHttpRequest.<anonymous> (https://ZZZZZ/XXthruk/vendor/extjs-4.2.2/ext-all.js:21:26493)
[2023/06/04 22:59:16][NagiosNode2][ERROR] Source:
[2023/06/04 22:59:16][NagiosNode2][ERROR] ---------------

The error does not come up

**Thruk Version**
3.05.20230520/ OMD 5.11~2023-05-20-labs-edition

**Expected behavior**

**Screenshots**
by clicking on map with error:
![image](https://github.com/sni/Thruk/assets/29919422/d2ab276e-6912-4167-8bb0-235190ab2aba)

after reload the site with in browser without error coming up:
![image](https://github.com/sni/Thruk/assets/29919422/0f00f462-2554-42c2-966b-deb881a66b90)

**Desktop (please complete the following information):**
Chrome 113.0.0.0 on Windows 10 64-bit

**Additional context**

**Comment by kafos** [comment]
Coming back to this after a long time — I think I found the cause, and it's still there in 3.29.

The stack trace from my original report points at an ajax callback reading `.id` of something undefined. That matches this in `panorama_js_functions.js` (line 1423 in 3.29.20260808):

```js
tab = Ext.getCmp(tab.id);
TP.iconUpdateRunning[tab.id] = false;
if(reschedule) { reschedule.unmask(); }
if(tab) { tab.removeMask(); }        // checked here, but already dereferenced two lines above
```

If the dashboard is gone by the time the status response arrives, `Ext.getCmp()` returns undefined and `tab.id` on the next line throws. The `if(tab)` check below shows the case was expected, it's just two lines too late.

That explains both halves of what I described back then:

**"fails to fully load the status"** — icons are fetched in batches of 20, and the exception happens in the callback of one batch. Everything after it, including `TP.insertStatusResponseData()`, never runs for that batch, so those icons keep their old state. On our map with 114 hostgroup icons that's one sixth of them at a time.

**"does not come up if i reload the site"** — the throw happens before `TP.iconUpdateRunning[tab.id] = false`, so the flag stays set. And `updateAllIconsDo()` starts with

```js
if(TP.iconUpdateRunning[tab.id]) { return; }
```

so every later refresh for that tab returns immediately, silently. A browser reload clears it, which is why reloading always "fixed" it.

You can see it while it's happening: `TP.iconUpdateRunning` in the console still shows `true` for the tab while nothing is updating, and setting `TP.iconUpdateRunning = {}` makes refreshes work again.

The same file gets it right in other places, e.g.

```js
var tab = Ext.getCmp(tab_id);
if(!tab) {
    // dashboard has been closed already
    return;
}
```

so this looks like an oversight rather than intent. Keeping the id in a local variable before the request, or just moving the null check up, should be enough.

One more thing that I think matters for why we hit this so often. The setup I reported it on had three levels: maps with hostgroups on them, those maps shown as a single status icon on a second level, and those again on a third. Sub-dashboards are loaded as hidden tabs on demand:

```js
if(!subtab) {
    TP.add_pantab({ id: subtab_id, hidden: true, callback: ... });
}
if(subtab && !subtab.rendered) {
    ...
    TP.iconUpdateRunning[subtab.id] = true;
```

so there are a lot of short-lived tabs around, which is exactly the situation where `Ext.getCmp()` comes back undefined.

And the flags for those sub-tabs are only cleared *after* the line that throws:

```js
tab = Ext.getCmp(tab.id);
TP.iconUpdateRunning[tab.id] = false;    // throws here
...
for(var key in subReqs) {
    TP.insertStatusResponseData(subReqs[key].tab, data.data.sub[key], subReqs[key].ref);
    TP.iconUpdateRunning[key] = false;   // never reached
}
```

So it isn't one dashboard that stops updating, it's the whole chain including every sub-dashboard in that request.

Also worth being aware of when looking at this: the batching code re-requests all sub-dashboard data once per batch instead of once per refresh, because the bucket variable changes from an object to an array after the first batch. I filed that separately. It doesn't cause this crash, but it multiplies the number and size of these requests, which widens the window for it.

Versions where I confirmed it now: Thruk 3.29.20260808 on OMD 5.71.20260808-labs-edition. Originally reported on 3.05.20230520 / OMD 5.11.

**Comment by sni** [comment]
thanks for the detailed analysis, i will have a look
