### ISSUE TITLE
Uncaught TypeError: search_name.toLowerCase is not a function

### ISSUE THREAD

**Issue by gerbier** [sni/Thruk#981]
**Describe the bug**
I have the following error in apache error_log file

[14:38:42,736][ERROR] JS-Error:
[14:38:42,736][ERROR] Version:    2.32~3
[14:38:42,736][ERROR] Release:    November 02, 2019
[14:38:42,736][ERROR] Url:        /thruk/side.html?
[14:38:42,736][ERROR] Browser:    Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/78.0.3904.97 Safari/537.36
[14:38:42,736][ERROR] Backends:   uname:      Linux sxreso1.cnrm.meteo.fr 5.3.7-server-4.mga7 #1 SMP Thu Oct 24 22:01:36 UTC 2019 x86_64
[14:38:42,737][ERROR] release:    Mageia release 7 (Official) for x86_64
[14:38:42,737][ERROR] Error List:
[14:38:42,737][ERROR] Url: http://thruk.cnrm.meteo.fr/thruk/cache/thruk-2.32-3.js Line 6756
[14:38:42,737][ERROR] Error: Uncaught TypeError: search_name.toLowerCase is not a function
[14:38:42,737][ERROR]
[14:38:42,737][ERROR] Full Stacktrace:
[14:38:42,737][ERROR] TypeError: search_name.toLowerCase is not a function
[14:38:42,737][ERROR]     at String.<anonymous> (http://thruk.cnrm.meteo.fr/thruk/cache/thruk-2.32-3.js:6756:51)
[14:38:42,737][ERROR]     at Function.each (http://thruk.cnrm.meteo.fr/thruk/cache/thruk-2.32-3.js:2:2777)
[14:38:42,738][ERROR]     at Object.<anonymous> (http://thruk.cnrm.meteo.fr/thruk/cache/thruk-2.32-3.js:6755:30)
[14:38:42,738][ERROR]     at Function.each (http://thruk.cnrm.meteo.fr/thruk/cache/thruk-2.32-3.js:2:2777)
[14:38:42,738][ERROR]     at Object.<anonymous> (http://thruk.cnrm.meteo.fr/thruk/cache/thruk-2.32-3.js:6742:26)
[14:38:42,738][ERROR]     at Function.each (http://thruk.cnrm.meteo.fr/thruk/cache/thruk-2.32-3.js:2:2777)
[14:38:42,738][ERROR]     at Object.suggest_do (http://thruk.cnrm.meteo.fr/thruk/cache/thruk-2.32-3.js:6732:20)
[14:38:42,738][ERROR]     at <anonymous>:1:13

**Thruk Version**
Version of Thruk (and OMD if applicable) : 2.32~3

**To Reproduce**

**Expected behavior**

**Desktop (please complete the following information):**
 - brave 1.0

**Additional context**

**Comment by sni** [comment]
no idea how you did that, but making search_name a string should fix it.
